apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: vault-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: vault-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: vault
        server: "{{server}}"
      project: default
      sources:
        - chart: vault
          repoURL: https://helm.releases.hashicorp.com
          targetRevision: 0.29.1
          helm:
            valuesObject:
              global:
                openshift: true
              injector:
                enabled: true
              server:
                enabled: true
                route:
                  enabled: true
                  host: vault.apps.ocp.k8socp.com
                  tls:
                    termination: edge
                ha:
                  enabled: true
                ui:
                  enabled: true
                csi:
                  enabled: true
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Replace=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: vault-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - local-cluster
